#!/usr/bin/env python

import sys
import os
import fnmatch
import re
import json

def quote(s):
	return "'%s'" % s

def main():

	print "// auto-generated by '%s'" % os.path.basename(__file__)

	paths = []
	for root, dirnames, filenames in os.walk('.'):
		for filename in fnmatch.filter(filenames, '*.json'):
			fullpath = os.path.join(root,filename)[2:]
			if fullpath.startswith('node_modules'):
				continue
			paths.append(fullpath)
	
	num_paths = len(paths)
	obj = {}
	for i,path in enumerate(paths):
		obj[path] = json.load(open(path))
	
	print "Ptero.jsonData =", json.dumps(obj,indent=4), ";"

if __name__ == "__main__":
	main()
