#!/usr/bin/env python

import sys
import os
import fnmatch
import re
import json

def quote(s):
	return "'%s'" % s

def main():

	print "// auto-generated by '%s'" % os.path.basename(__file__)

	paths = []
	for root, dirnames, filenames in os.walk('swf'):
		for filename in fnmatch.filter(filenames, '*.json'):
			fullpath = os.path.join(root,filename)
			if "_mountain_" in fullpath:
				paths.append(fullpath)

	"""
	for root, dirnames, filenames in os.walk('bg/mountain/'):
		for filename in fnmatch.filter(filenames, '*.json'):
			fullpath = os.path.join(root,filename)
			if not "red" in fullpath and not "white" in fullpath:
				paths.append(fullpath)
	"""
	
	num_paths = len(paths)
	obj = {}
	for i,path in enumerate(paths):
		obj[path] = json.load(open(path))
	
	print json.dumps(obj,indent=4)

if __name__ == "__main__":
	main()
