// auto-generated by 'genParallaxJsonData.py'
Ptero.jsonData = {
	"bg.jpg.json": {
		"scale": 1
	},
	"ptero_paths.json": {
		"version": 1,
		"models": [
			{
				"index": 1,
				"enemyType": "baby_mountain_blue",
				"points": [
					{
						"t": 0,
						"x": -2.2947884147290414,
						"y": 1.193586756835941,
						"z": 10.947555555555557,
						"angle": 0
					},
					{
						"t": 0.8549533636407102,
						"x": -0.7132114045200353,
						"y": 0.8258463645176879,
						"z": 6.810387956922131,
						"angle": 0
					},
					{
						"t": 3.836363636363638,
						"x": -0.09529382104221854,
						"y": -0.077237115561657,
						"z": 1.5404444444444463,
						"angle": 0
					}
				]
			},
			{
				"index": 3,
				"enemyType": "baby_mountain_purple",
				"points": [
					{
						"t": 0.43636363636363634,
						"x": -1.486476870050065,
						"y": 2.4712404887478714,
						"z": 10.947555555555557,
						"angle": 0
					},
					{
						"t": 1.5822260909134382,
						"x": 0.1464900312097089,
						"y": 0.9393918371612391,
						"z": 6.810387956922131,
						"angle": 0
					},
					{
						"t": 3.43636363636364,
						"x": 0.28994963417342046,
						"y": 0.07319128123683048,
						"z": 1.5404444444444463,
						"angle": 0
					}
				]
			},
			{
				"index": 4,
				"enemyType": "adult_mountain_green",
				"points": [
					{
						"t": 0.9818181818181818,
						"x": 0.9048733805663175,
						"y": 3.5263678554768534,
						"z": 10.542222222222223,
						"angle": 0
					},
					{
						"t": 2.9500679090907465,
						"x": -0.05284954383132838,
						"y": 0.8682151870289996,
						"z": 7.254459976645942,
						"angle": 0
					},
					{
						"t": 5.218181818181819,
						"x": 0,
						"y": 0,
						"z": 1.9457777777777796,
						"angle": 0
					}
				]
			}
		]
	},
    "swf/pteros/baby_mountain_purple/3.svg.json": {
        "width": 11000, 
        "vector": true, 
        "scale": 0.09, 
        "height": 8000
    }, 
    "swf/pteros/baby_mountain_purple/7.svg.json": {
        "width": 11000, 
        "vector": true, 
        "scale": 0.09, 
        "height": 8000
    }, 
    "swf/pteros/baby_mountain_blue/8.svg.json": {
        "width": 11000, 
        "vector": true, 
        "scale": 0.09, 
        "height": 8000
    }, 
    "swf/pteros/adult_mountain_green/8.svg.json": {
        "width": 30000, 
        "vector": true, 
        "scale": 0.072, 
        "height": 20000
    }, 
    "swf/pteros/adult_mountain_green/6.svg.json": {
        "width": 30000, 
        "vector": true, 
        "scale": 0.072, 
        "height": 20000
    }, 
    "swf/pteros/baby_mountain_purple/2.svg.json": {
        "width": 11000, 
        "vector": true, 
        "scale": 0.09, 
        "height": 8000
    }, 
    "swf/pteros/baby_mountain_blue/4.svg.json": {
        "width": 11000, 
        "vector": true, 
        "scale": 0.09, 
        "height": 8000
    }, 
    "swf/pteros/baby_mountain_purple/1.svg.json": {
        "width": 11000, 
        "vector": true, 
        "scale": 0.09, 
        "height": 8000
    }, 
    "swf/pteros/baby_mountain_blue/6.svg.json": {
        "width": 11000, 
        "vector": true, 
        "scale": 0.09, 
        "height": 8000
    }, 
    "swf/pteros/adult_mountain_red/0.svg.json": {
        "width": 30000, 
        "vector": true, 
        "scale": 0.072, 
        "height": 20000
    }, 
    "swf/pteros/adult_mountain_red/1.svg.json": {
        "width": 30000, 
        "vector": true, 
        "scale": 0.072, 
        "height": 20000
    }, 
    "swf/pteros/adult_mountain_green/3.svg.json": {
        "width": 30000, 
        "vector": true, 
        "scale": 0.072, 
        "height": 20000
    }, 
    "swf/pteros/baby_mountain_purple/0.svg.json": {
        "width": 11000, 
        "vector": true, 
        "scale": 0.09, 
        "height": 8000
    }, 
    "swf/pteros/adult_mountain_red/3.svg.json": {
        "width": 30000, 
        "vector": true, 
        "scale": 0.072, 
        "height": 20000
    }, 
    "swf/pteros/baby_mountain_purple/5.svg.json": {
        "width": 11000, 
        "vector": true, 
        "scale": 0.09, 
        "height": 8000
    }, 
    "swf/pteros/adult_mountain_green/5.svg.json": {
        "width": 30000, 
        "vector": true, 
        "scale": 0.072, 
        "height": 20000
    }, 
    "swf/pteros/adult_mountain_green/4.svg.json": {
        "width": 30000, 
        "vector": true, 
        "scale": 0.072, 
        "height": 20000
    }, 
    "swf/pteros/adult_mountain_red/5.svg.json": {
        "width": 30000, 
        "vector": true, 
        "scale": 0.072, 
        "height": 20000
    }, 
    "swf/pteros/adult_mountain_red/8.svg.json": {
        "width": 30000, 
        "vector": true, 
        "scale": 0.072, 
        "height": 20000
    }, 
    "swf/pteros/baby_mountain_blue/1.svg.json": {
        "width": 11000, 
        "vector": true, 
        "scale": 0.09, 
        "height": 8000
    }, 
    "swf/pteros/baby_mountain_blue/5.svg.json": {
        "width": 11000, 
        "vector": true, 
        "scale": 0.09, 
        "height": 8000
    }, 
    "swf/pteros/baby_mountain_blue/0.svg.json": {
        "width": 11000, 
        "vector": true, 
        "scale": 0.09, 
        "height": 8000
    }, 
    "swf/pteros/adult_mountain_red/6.svg.json": {
        "width": 30000, 
        "vector": true, 
        "scale": 0.072, 
        "height": 20000
    }, 
    "swf/pteros/baby_mountain_blue/3.svg.json": {
        "width": 11000, 
        "vector": true, 
        "scale": 0.09, 
        "height": 8000
    }, 
    "swf/pteros/baby_mountain_purple/6.svg.json": {
        "width": 11000, 
        "vector": true, 
        "scale": 0.09, 
        "height": 8000
    }, 
    "swf/pteros/baby_mountain_purple/4.svg.json": {
        "width": 11000, 
        "vector": true, 
        "scale": 0.09, 
        "height": 8000
    }, 
    "swf/pteros/adult_mountain_green/7.svg.json": {
        "width": 30000, 
        "vector": true, 
        "scale": 0.072, 
        "height": 20000
    }, 
    "swf/pteros/adult_mountain_red/4.svg.json": {
        "width": 30000, 
        "vector": true, 
        "scale": 0.072, 
        "height": 20000
    }, 
    "swf/pteros/adult_mountain_green/1.svg.json": {
        "width": 30000, 
        "vector": true, 
        "scale": 0.072, 
        "height": 20000
    }, 
    "swf/pteros/baby_mountain_purple/8.svg.json": {
        "width": 11000, 
        "vector": true, 
        "scale": 0.09, 
        "height": 8000
    }, 
    "swf/pteros/adult_mountain_red/2.svg.json": {
        "width": 30000, 
        "vector": true, 
        "scale": 0.072, 
        "height": 20000
    }, 
    "swf/pteros/adult_mountain_green/2.svg.json": {
        "width": 30000, 
        "vector": true, 
        "scale": 0.072, 
        "height": 20000
    }, 
    "swf/pteros/baby_mountain_blue/2.svg.json": {
        "width": 11000, 
        "vector": true, 
        "scale": 0.09, 
        "height": 8000
    }, 
    "swf/pteros/baby_mountain_blue/7.svg.json": {
        "width": 11000, 
        "vector": true, 
        "scale": 0.09, 
        "height": 8000
    }, 
    "swf/pteros/adult_mountain_red/7.svg.json": {
        "width": 30000, 
        "vector": true, 
        "scale": 0.072, 
        "height": 20000
    }, 
    "swf/pteros/adult_mountain_green/0.svg.json": {
        "width": 30000, 
        "vector": true, 
        "scale": 0.072, 
        "height": 20000
    }
} ;
